version: "3.9"
services:

  sql-data:
    image: sqldata
    environment:
     ACCEPT_EULA: "Y"
     SA_PASSWORD: "Pa$$w0rd16"
     MSSQL_SA_PASSWORD: "Pa$$w0rd16"
     MSSQL_PID: Express
    ports:
     - "1433:1433" 

  subscription:
    image: hushvi/service-subs
    environment: 
     DBServer: "sql-data"
    ports:
      - 8081:80

  team:
    image: hushvi/service-teams
    environment: 
     DBServer: "sql-data"
    ports:
      - 8082:80

  games:
    image: hushvi/service-games
    environment: 
     DBServer: "sql-data"
    ports:
      - 8083:80

  news:
    image: hushvi/service-news
    environment: 
     DBServer: "sql-data"
    ports:
      - 8084:80